# Generated by Django 4.2.6 on 2023-11-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_card_loan_transaction_loanpayment_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
