# Generated by Django 4.2.6 on 2023-11-14 23:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_transaction_card_alter_transaction_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='url_image',
            field=models.ImageField(default=None, null=True, upload_to=core.models.user_image_field),
        ),
    ]
